# Generated by Django 5.1.3 on 2024-12-07 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_areastatus_areatypes_clients_elevatormodels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypes',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_types',
            },
        ),
        migrations.AlterModelOptions(
            name='areastatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='areatypes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={},
        ),
        migrations.AlterModelOptions(
            name='elevatormodels',
            options={},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
        migrations.AlterField(
            model_name='projectassignmentareapersonnel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='ElevatorConfigurations',
            fields=[
                ('configuration_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('door_type', models.CharField(blank=True, max_length=50, null=True)),
                ('power_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('certification', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
            options={
                'db_table': 'elevator_configurations',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.elevatormodels')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
            options={
                'db_table': 'inventory_transactions',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequests',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personnel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
            options={
                'db_table': 'maintenance_requests',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_done', models.TextField()),
                ('parts_used', models.CharField(blank=True, max_length=255, null=True)),
                ('hours_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maintenancerequests')),
            ],
            options={
                'db_table': 'maintenance_logs',
            },
        ),
        migrations.CreateModel(
            name='Proformas',
            fields=[
                ('proforma_id', models.AutoField(primary_key=True, serialize=False)),
                ('proforma_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
            ],
            options={
                'db_table': 'proformas',
            },
        ),
    ]
