# Generated by Django 5.1.3 on 2024-12-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sales_options_personnel_area_projects_sale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
    ]
