# Generated by Django 5.1.3 on 2024-12-10 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.clients'),
        ),
        migrations.AddField(
            model_name='sales',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.elevatormodels'),
        ),
    ]
