# Generated by Django 5.1.3 on 2025-02-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_projectassignmentareapersonnel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
    ]
