# Generated by Django 5.1.3 on 2025-02-03 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sales_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='proforma_date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='proforma_id',
        ),
        migrations.AddField(
            model_name='sales',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.proformas'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clients'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
