# Generated by Django 5.1.3 on 2025-02-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_proforma_date_sales_payment_date_and_more'),
    ]

    operations = [
    ]
