# Generated by Django 5.1.3 on 2025-02-04 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20250203_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassignmentareapersonnel',
            options={},
        ),
    ]
