# Generated by Django 5.1.3 on 2025-02-04 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_projectassignmentareapersonnel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignmentareapersonnel',
            name='area',
            field=models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='api.areatypes'),
        ),
        migrations.AlterField(
            model_name='projectassignmentareapersonnel',
            name='area_status',
            field=models.ForeignKey(blank=True, db_column='area_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.areastatus'),
        ),
        migrations.AlterField(
            model_name='projectassignmentareapersonnel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectassignmentareapersonnel',
            name='personnel',
            field=models.ForeignKey(db_column='personnel_id', on_delete=django.db.models.deletion.CASCADE, to='api.personnel'),
        ),
        migrations.AlterField(
            model_name='projectassignmentareapersonnel',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='api.projects'),
        ),
    ]
