# Generated by Django 5.1.3 on 2025-02-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_projectassignmentareapersonnel_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformas',
            name='is_converted_to_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sales'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='proforma',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.proformas'),
        ),
    ]
